monasca-forwarder/Dockerfile, monasca-forwarder/README.md, monasca-forwarder/build.sh, monasca-forwarder/forwarder.conf.j2, monasca-forwarder/forwarder_metric_match.yml.j2, monasca-forwarder/kafka_wait_for_topics.py, monasca-forwarder/start.sh, monasca-forwarder/template.py
Did not add it to docker-compose.yml since it can't be used in a normal deployment
=> Added Forwarder

ci.py, kafka/README.md, kafka/build.yml
This makes a number of build script changes to add deployment logic.
Note that actual deployment operations are no-op'd while some Travis
details are resolved.
=> Add initial Travis deployment logic

job-cleanup/Dockerfile, job-cleanup/README.md, job-cleanup/build.yml, job-cleanup/cleanup.py
This adds a new job cleanup script/container, intended to clean up old
Kubernetes jobs during an upgrade.
=> Add K8s job cleanup container

monasca-api-python/Dockerfile
Modifies Dockerfile to do a git checkout that fetches any branch
specified with the API_BRANCH argument
=> Change git checkout to look for upstream repo

job-cleanup/Dockerfile, job-cleanup/build.yml, job-cleanup/cleanup.py, job-cleanup/kubernetes.py
The python kubernetes client is a giant mess, so we're abandoning it.
=> Fix job-cleanup

monasca-notification/build.yml, monasca-notification/notification.yaml.j2
Also include date and time in master tags.
=> Add template option to the hipchat notifier

monasca-alarms/build.yml, monasca-alarms/definitions.yml.j2
It was missing for two of them
=> Add match-by for all alarm definitions

job-cleanup/kubernetes.py
This doesn't change anything for job-cleanup, so no version bump.
=> Honor KUBECONFIG env var in kubernetes client

tempest-tests/start.sh
=> Replace hard coded project name

monasca-agent-base/Dockerfile, monasca-agent-base/README.md, monasca-agent-base/agent.yaml.j2, monasca-agent-base/build.sh, monasca-agent-base/build.yml, monasca-agent-base/kubernetes_get_host.py, monasca-agent-base/template.py
Will be used for separate collector and forwarder images once
this has been merged and the image uploaded to docker hub
This image has the source code, all dependencies and anything
else that would be needed by both the forwarder and collector
=> Create new agent base image

docker-compose.yml
It needed to be built first so this is a separate change
=> Use new version of grafana

keystone-init/Dockerfile, keystone-init/build.yml
tini will allow the container to handle signals properly
=> Add tini to keystone-init

ci.py
Add execution of the tempest inside the CI setup.
=> Tempest in CI

ci.py, docker-compose.yml
Also, use real tags in more places in docker-compose.yml.
=> Add kafka-init to ci.py

monasca-agent-collector/Dockerfile, monasca-agent-forwarder/Dockerfile
Note: make sure to include `!push` in the merge commit for this PR
=> Update agent-collector and agent-forwarder to use new base image

monasca-agent-collector/Dockerfile, monasca-agent-forwarder/Dockerfile
Collector will pick up https://review.openstack.org/499835
=> Update agent containers to use new agent base

LICENSE, License
=> Add software license

monasca-thresh/Dockerfile, storm/build.yml, storm/entrypoint.sh
Use [ ! -f "$f" ] to assert files instead of  [ ! -e "$f" ]
Closes #246
=> exclude non file types

influxdb-init/build.yml, influxdb-init/init.sh
=> Fix some linter warnings, part 7b2

kafka-init/build.yml
bumping version for kafka-init
=> Fix some lint errors, part 7b3

monasca-forwarder/start.sh, monasca-log-agent/build.yml, monasca-log-agent/start.sh
=> Fix some linter warnings, part 13

monasca-log-api/start.sh, monasca-log-metrics/start.sh
=> Fix some linter warnings, part 20

monasca-log-persister/template.py, monasca-log-transformer/template.py
=> Fix Python linter error - Part 10

grafana/template.py, monasca-notification/template.py
=> Fix Python linter error - Part 6

grafana-init/grafana.py, monasca-persister-python/template.py
=> Fix Python linter error - Part 8

storm/build.yml, storm/entrypoint.sh, storm/templates/storm.yaml.j2
1. Missing = sign after MaxRAM args
2. UI_HOST and UI_PORT are too generic of names allowing for
collisions. Prepend with STORM_
=> Fix various storm issues

kafka-watcher/build.yml
The previous version did not build
=> Bump kafka-watcher version

monasca-agent-collector/build.yml, monasca-agent-forwarder/build.yml
Only really need it for collector as I want to pick up the
autorestart change, but good to keep the two in sync to reduce
image pull time
=> Use new agent base for collector and forwarder

kafka-watcher/build.yml
With latest changes from monasca-watchers
=> Build new kafka-watcher

monasca-agent-collector/README.md
Add new restart configuration options
=> Update monasca-agent-collector README

grafana/Dockerfile, grafana/build.yml
Install discrete panel plugin and enable to use discrete panel.
=> Make it possible to use grafana discrete panel

monasca-thresh/Dockerfile, monasca-thresh/submit.sh
Need the UI_PORT to STORM_UI_PORT fix
Need quotes in if statement otherwise we get a syntax error when
trying to run with storm
=> Use new storm container for thresh

monasca-agent-collector/build.yml, monasca-agent-forwarder/build.yml
Need it only for the Forwarder to pick up the
max_batch_size change, but let's keep both in sync.
=> Use new Agent Base Container

kafka-watcher/build.yml, zookeeper-watcher/build.yml
Pick up various bug fixes such as:
1. Write Failures metric was not being updated
2. Zookeeper watcher failed to create path
=> Update Kafka and Zookeeper Watcher Versions

monasca-thresh/Dockerfile
=> Add py-setuptools to monasca-thresh image

influxdb-watcher/README.md, influxdb-watcher/build.yml
Pulls in https://github.com/monasca/monasca-watchers/pull/12
Signed-off-by: Andrea Adams aadams@hpe.com
=> Bump InfluxDB-Watcher to include read bug fix

kafka/Dockerfile, kafka/build.yml, kafka/kafka_mirror.py, kafka/templates/server.properties.j2
=> Make Kafka's `connections.max.idle.ms` configurable

docs/README.md, docs/elasticsearch.md, docs/requirements.md, log-pipeline.yml
Also update log-pipeline.yml with simpler env variable for setting heap
size for Elasticsearch.
=> Add information to docs about configuring host for ES

monasca-log-api/build.yml
=> Bump log-api version

monasca-log-api/Dockerfile
=> Add missing dependencies

monasca-agent-base/apk_install.sh
=> Add dependencies to build monasca-common

monasca-agent-collector/Dockerfile
=> Add missing lscpu for cpu metrics

monasca-agent-collector/build.yml, monasca-agent-forwarder/build.yml
=> Update agent-collector and agent-forwarder

docs/README.md
Add information on how to access deployed services to Quick Start
document.
Signed-off-by: Witek Bedyk <witold.bedyk@suse.com>
=> Add information to Quick Start document

log-pipeline.yml
Added STATSD_HOST and STATSD_PORT settings to the log-api environment configuration.
=> Added STATSD default parameters for log-api

kafka-init/build.yml, kafka/build.yml, mysql-init/build.yml
!push kibana
!push monasca-agent-collector
=> Fixing tags in build.yml files.
