k8s/forwarder/forwarder.yml
monasca-api-python/README.md
monasca-api-python/api-config.conf.j2

This is in a subdirectory of k8s and not in monasca-start.sh because the
forwarder isn't part of a normal deploy.

Add k8s file for forwarder

---

monasca-transform/Dockerfile

Now that kubernetes metrics aggregation is now available and the late metrics
aggregation timing is merged to master we can simplify the docker image
generation to just use the master branch of monasca-transform.

Use master branch of monasca-transform

---

.travis.yml
ci.py
mysql-init/build.yml
storm/build.yml

This adds an initial .travis.yml with a ci.py. ci.py uses dbuild [1]
to manage container building, with some extra logic to only build
modules changed in each PR's commit range. This initial commit only
does a simply build pass/fail check, but future additions should allow
for automatic deployment and README updates on Docker Hub.
[1] https://github.com/timothyb89/dbuild

Add travis-ci configuration and build scripts

---

docker-compose.yml
grafana/Dockerfile
grafana/build.yml

The container now includes [monasca-grafana-app](https://github.com/stackhpc/monasca-grafana-app) and builds from [sapcc's grafana branch](https://github.com/sapcc/grafana/tree/grafana4) by default

Update Grafana container and add monasca-grafana-app

---

keystone/Dockerfile
keystone/README.md
keystone/build.yml
keystone/k8s_get_service.py
keystone/keystone-bootstrap.sh
keystone/preload.py
keystone/preload.yml
keystone/start.sh

This adds new functionality to the Keystone container to allow it to
auto-detect external (public and admin) URLs when creating catalog
entries. This only works in Kubernetes environments with
KUBERNETES_RESOLVE_PUBLIC_ENDPOINTS=true and
KEYSTONE_SERVICE_NAME set to the name of the keystone service. The
end result of this is that Keystone can be used from outside of a
Kubernetes without any routing issues.
Services in preload.yml can also use the new functionality. By adding
`resolve: true` to an 'interfaces:' entry, the service will be looked
up in the Kubernetes API based on the URL and replaced with the
correct publicly-accessible node or ingress IP and port.

Add support for auto-detecting external Keystone endpoints in k8s

---

storm/Dockerfile

Storm isn't compatible with the busybox `ps` implementation. This adds
the more traditional `procps` package so storm's subprocess management
can work as expected.

Add procps to storm container

---

monasca-agent/Dockerfile

Honoring OpenStack's upper constraints makes alpine's python-lxml
invalid. This adds the necessary development packages for pip to
build lxml from source.

Fix monasca-agent build

---

docker-compose.yml
mysql-init/Dockerfile
mysql-init/build.yml
mysql-init/init.sh
mysql-init/mysql-init.d/00-monasca.sql.j2
mysql-init/mysql-init.d/99-version-schema.sql.j2

This add very preliminary 'upgrade' support to mysql init. mysql-init
now automatically creates a schema version table and checks versions
during init. Eventually it will use this table to apply upgrades
sequentially based on the current installed schema version.
Note that actual upgrade logic will come in a future PR. This patch
is mainly intended to make mysql-init return successfully when run
against an existing database. If an existing version is found it will
print the version but will not process the `mysql-upgrades.d`
directory yet.

Add basic upgrade support to mysql-init

---

docker-compose.yml
monasca-alarms/Dockerfile
monasca-alarms/README.md
monasca-alarms/build.yml
monasca-alarms/definitions.yml
monasca-alarms/monasca_alarm_definition.py
monasca-alarms/start.sh

Container runs once to create Notifications and Alarm Definitions
in Monasca. The creation command checks first if the Notification
or Alarm Definition exists and matches what is expected. If it
matches, nothing is done so this container is idempotent.

Add container to create Notifications and Alarm Definitions

---

docker-compose.yml
monasca-alarms/Dockerfile
monasca-alarms/build.yml
monasca-alarms/definitions.yml.j2
monasca-alarms/start.sh
monasca-alarms/template.py

This makes the default notification method type and address
configurable at runtime.

Add jinja2 templating to monasca-alarms

---

ci.py

Currently `ci.py` won't try to push unless build.yml is changed. This works alright for most standard semver images, but it makes `master-{date}-{time}`-style image tags incompatible with our CI.
This adds support for building using a flag in the commit message, `!push`. When `!push module` is included in a merge commit message (on its own line), `ci.py` will build and push the image regardless of whether or not the `build.yml` has changed.

Support forcing a push for an unchanged build.yml via commit message

---

monasca-thresh/submit.sh

Also, forces a new build of the thresh container to pick up the
new storm container which has additional configuration env
vars
!push monasca-thresh

Add print of thresh config file

---

monasca-api-python/start.sh

Added setting of PYTHON_ENCODING. Seems like it would not be needed
but testing shows it is

Monasca API did not handle non ascii characters

---

docker-compose.yml

docker-compose in 3rd version offers compatybility with docker's
swarm mode. Since docker-compose in current shape works for
3rd version, the change is painless and allows to deploy monasca
over swarm with Docker (at least) 1.13 as in:
```docker deploy --compose-file docker-compose.yml mon```

Increase docker-compose version up to 3

---

monasca-api-python/Dockerfile
monasca-api-python/README.md
monasca-api-python/api-config.conf.j2
monasca-api-python/api-logging.conf.j2
monasca-api-python/start.sh

It goes to stderr with other logging. It is marked by having
gunicorn.access in the line.
In addition, modify the config file to remove deprecation
warnings.

Add API access log

---

monasca-api-python/api-config.conf.j2

This allows us to support newer versions of the API. Otherwise,
it fails with:
AttributeError: 'NoneType' object has no attribute 'rpartition'

Add healthchecks to conf file

---

monasca-thresh/build.yml
storm/build.yml

monasca-thresh did not define the latest alias
storm version was not semver compliant

Fix build.yml files

---

docker-compose.yml

Currently the agent does not collect any metrics when running in
docker-compose. The docker plugin can't run now that the collector
is running as mon-agent (even with the socket mounted) and probably
needs a lot of refactoring to make it work well. As an alternative,
we now include cAdvisor by default and enable the cAdvisor plugin.
While the cAdvisor plugin only collects host-level metrics and does
not collect container metrics, it at least gets metrics flowing
through the system. Additionally, we can use cAdvisor as a base for
docker container monitoring in the future when the docker plugin is
refactored.

Enable cadvisor plugin by default in docker-compose

---

.travis.yml

Instead of relying on the docker engine provided
by Travis, let's install latest available
version from official Docker Repository.
Closes #80

Upgrade docker to enable multi-stage builds

---

ci.py
docker-compose.yml
monasca-thresh/Dockerfile
monasca-thresh/README.md
monasca-thresh/kafka_wait_for_topics.py
monasca-thresh/submit.sh

Allow the Threshold Engine to optionally run without Storm Nimbus and
Supervisor daemons. Make this the default configuration so remove
Nimbus and Supervisor from docker-compose.yml
Update ci.py for new and removed containers
Fixed CI test for number of jobs

Allow Thresh to run without storm

---

monasca-api-python/README.md
monasca-api-python/api-config.conf.j2
monasca-api-python/start.sh

This allows just the metrics part of Monasca to run assuming
an external keystone is available
Attempting to query notifications, alarm definitions or alarms
will result in a 500. Use very carefully

Allow API to start without a Mysql database

---

docker-compose.yml

In monasca upstream, Zookeeper 3.4 is currently used.
However monasca-docker still uses 3.3.
Partially-handles #135

Bump Zookeeper to 3.4

---

monasca-api-python/build.yml

Updates the API to use the latest version of the prometheus patch [1], rebased on monasca-api HEAD [2] as of 2 August 2017.
[1] https://review.openstack.org/#/c/417163/
[2] 1a0c02bbf9084229150b29e837df7fbe1d9848d7

Update monasca-api branch

---

keystone-init/Dockerfile
keystone-init/build.yml
keystone-init/keystone_init.py
keystone-init/kubernetes.py
keystone-init/preload.yml
keystone-init/requirements.txt
keystone-init/stack-fix.c
keystone-init/start.sh

This adds a new container capable of creating accounts in keystone.
It randomly generates passwords at first start and stores them in
Kubernetes secrets, bypassing Helm so that the secrets can be stored
securely.
Note that the container currently requires a Kubernetes environment,
support for running in docker will be added in the future. Eventually
this should replace most of our keystone bootstrapping logic.

Add keystone-init container

---

monasca-python/Dockerfile.example
monasca-python/build.sh

Short flags, composed out of two letters, do not work
with getopt utility.

Couple fixes for monasca/python

---

keystone-init/README.md
keystone-init/build.yml
keystone-init/keystone_init.py

- add a README.md
- remove hard dependency on k8s
(caveat in docker is plaintext passwords, explained in README)
- provide more Keystone variables in generated k8s Secrets
(auth URL, user domain, project name+domain)

Misc keystone-init improvements

---

docker-compose.yml
kafka-init/Dockerfile
kafka-init/README.md
kafka-init/build.yml
kafka-init/create_topics.py
kafka-init/wait-for.sh

Depends-On: #138 
Closes: #134

Add kafka-init container

---

mysql-users-init/Dockerfile
mysql-users-init/README.md
mysql-users-init/build.yml
mysql-users-init/kubernetes.py
mysql-users-init/mysql_init.py
mysql-users-init/preload.yml
mysql-users-init/requirements.txt
mysql-users-init/stack-fix.c
mysql-users-init/start.sh

This adds a new init job that can create users and databases in MySQL,
storing generated credentials in Kubernetes secrets.
Note that this job does not currently handle schema upgrades.
In the future it will either complement or replace the existing
mysql-init job.

Add mysql-users-init container

---

mysql-users-init/build.yml
mysql-users-init/mysql_init.py

This adds support for resetting mysql passwords when a Kubernetes secret is lost. This should allow clusters to recover persistently stored data in mysql if a k8s cluster (and all the passwords stored in Secrets) is lost.
Also, fixes various string escaping issues.

Support resetting user passwords in mysql-users-init

---

README.md

Fix "log-pipeline" section of document to configure correct environment
variable of Keystone URL because different Keystone URL variable is used
for kibana and log-api.

Fix info about using external Keystone

---

keystone/build.yml
keystone/k8s_get_service.py

In k8s 1.7 the URL validation is more strict so getting `//api/...`
raises an error. This patches api_get to remove a leading `/`
character in case it gets passed in.

Trim leading slash in k8s_get_service

---

monasca-notification/notification.yaml.j2

The value of e-mail timeout has quotation marks and it is treated as a
string. This patch removes the quatations to treat the timeout value as
integer.

Fix e-mail timeout

---

README.md

This will link host machine time to time in the containers so we will have same time in docker output logs.

Sync containers time with host time

---

mysql-init/README.md
mysql-init/build.yml
mysql-init/init.sh
mysql-init/mysql-init.d/01-keystone.sql.j2
mysql-init/mysql-init.d/02-users.sql.j2
mysql-init/mysql-init.d/03-grafana.sql.j2
mysql-init/mysql-upgrade.d/1.5.0/01-grafana.sql.j2

Allow skipping of creating the database for Keystone. Useful when
using an external Keystone.
Allow skipping of creating mon database users if they have been
created externally.
Allow skipping of Grafana database if it is not configured.

Make parts of mysql-init optional

---

grafana/Dockerfile

"yarn" which is newer than v0.28 doesn't work with nodejs newer than
4.x. This patch force to use yarn v0.27.

Use yarn v0.27

---

docker-compose.yml

By design the Monasca Agent Collector exits every 24 hours because
there have been problems with massive memory growth. Set restart
policy to on-failure so it will auto restart in this case.

Set restart policy for monasca-collector

---

grafana/Dockerfile
grafana/README.md
grafana/grafana.ini.j2
grafana/start.sh
grafana/template.py

The initialization file for grafana was not configurable by using
enrironmental variables during the startup of the container. This commit
makes it possible to configure Grafana admin user name and password of
the file.

Make Grafana admin user configurable

---

monasca-agent-base/Dockerfile
monasca-agent-base/apk_install.sh
monasca-agent-base/build.yml

monasca/python provides a foundation for the Python
monasca components and several features & fixes that
concern and affects all Python applications.
!push monasca-agent-base

Use monasca/python for monasca/agent-base

---

monasca-client/Dockerfile
monasca-client/build.yml

monasca/python provides a foundation for the Python
monasca components and several features & fixes that
concern and affects all Python applications.
!push monasca-client

Use monasca/python for monasca/client

---

ci.py

Building of images is duplicated between
pipelines. This change removes that flaw, hence
only pipeline specific modules will be taken
into consideration for it.
Common modules, shared between pipelines, are built
regardless of the pipeline at the moment.

CI: Build only required modules per pipeline

---

ci.py

An error has been introduced in the ci.py in the
change that was minimizing amount of the modules
being build for single pipeline.
To fix: iterate over all planned modules and only
pick those that are members of active pipeline.

Fix the ci.py module's picking

---

monasca-log-persister/kafka_wait_for_topics.py
monasca-log-persister/start.sh
monasca-log-persister/template.py
monasca-log-transformer/kafka_wait_for_topics.py
monasca-log-transformer/start.sh
monasca-log-transformer/template.py
monasca-notification/kafka_wait_for_topics.py
monasca-notification/start.sh
monasca-notification/template.py
monasca-persister-python/kafka_wait_for_topics.py
monasca-persister-python/start.sh
monasca-persister-python/template.py

PR #204 fails because changes are made in more than 5 modules.
This PR reproduces changes made in PR #204 to 4 modules: 
- monasca-notification
- monasca-log-persister
- monasca-log-transformer
- monasca-persister-python
The remaining modules remain in the original PR (part 4.1)

Fix some linter warnings, part 4.2

---

grafana/start.sh
monasca-agent-base/Dockerfile
monasca-agent-collector/README.md
monasca-agent-collector/start.sh
monasca-agent-forwarder/README.md
monasca-agent-forwarder/start.sh
monasca-alarms/Dockerfile
monasca-alarms/README.md
monasca-alarms/start.sh

A recent change to python-monascaclient removed ksclient, so using python-keystoneclient is now necessary to get a token to authenticate with the monasca client.
The keystone variables should only be set if they are not provided so that there is backwards compatibility with keystone v2

Configure keystone && fix alarms to work with new python-monascaclient

---

docker-compose.yml

restart: on-failure for Zookeeper, Kafka, and monasca-persister
See issue  #237
https://github.com/monasca/monasca-docker/issues/237

Add restart for ZK, Kafka and monasca-persister

---

ci.py

CI should check the alarms and grafana-init containers for success or failure, and error on failure.

Add alarms and grafana-init to metrics pipeline

---

grafana/build.yml
grafana/start.sh

Fix some lint errors, part 7b1

---

monasca-log-persister/build.yml
monasca-log-persister/start.sh
monasca-log-transformer/build.yml
monasca-log-transformer/start.sh

Fix some linter warnings, part 14

---

monasca-persister-python/start.sh
monasca-python/build.sh

!push monasca-persister-python
!push monasca-python

Fix some linter warnings, part 16

---

storm/build.yml
storm/entrypoint.sh
tempest-tests/build.yml
tempest-tests/start.sh

Fix some linter warnings, part 18

---

grafana/start.sh
monasca-log-agent/start.sh

fixes some errors for #263 (formerly #191)

Fix some linter warnings, part 19

---

README.md

Change the travis badge to refer to latest build from *stable/pike*

Display progress from stable/pike

---

monasca-thresh/submit.sh

PR made from upstream branch (not fork) to avoid timeout in Travis
!push monasca-thresh

Fix some linterwarnings, part 21 (from upstream)

---

kafka/Dockerfile
kafka/build.yml
kafka/memory.py
kafka/start.sh
monasca-thresh/README.md
monasca-thresh/submit.sh
storm/Dockerfile
storm/README.md
storm/build.yml
storm/entrypoint.sh
storm/memory.py

Right now we only limit stack size and heap but that is not the
whole jvm causing OOM issues. The max ram option should cap all
memory used by the JVM

Change jvm options to MAXRAM

---

monasca-agent-collector/README.md
monasca-agent-collector/templates/cadvisor_host.yaml.j2
monasca-agent-collector/templates/kubernetes.yaml.j2

This will help alleviate the stress we are putting on Monasca
in a confined environment.
TODO: make whitelists dynamic

Add optional whitelist to cadvisor host and k8s plugins

---

monasca-python/build.sh

The change made the getopt call check for success instead of failure.

Fix getopt call in monasca-python/build.sh

---

monasca-client/build.yml

The merge build for https://github.com/monasca/monasca-docker/pull/311 failed because of the bug fixed in #314. This updates `monasca/client` to use the new image so the build can pass again.

Use valid python base image for monasca/client 1.8.0 and master

---

monasca-client/Dockerfile

git was missing from the image causing the client build to fail.

Add git to monasca/client build

---

kafka/README.md
kafka/build.yml
kafka/start.sh

This will allow debugging of error conditions and handling problems
like a full disk.

Allow kafka container to stay alive after kafka exits

---

keystone-init/README.md
keystone-init/build.yml
keystone-init/keystone_init.py

Adds 'domain_roles' to the user object which acts similarly to 'roles' but applied
to the domain element of which the user is a child.

Add 'domain_roles' to user object

---

keystone-init/README.md
keystone-init/build.yml
keystone-init/keystone_init.py
keystone-init/preload.yml

Allow elements in domain.groups to be dictionaries containing
name and project_roles, each of which must have a 'project' and
list of 'roles' to be granted

Allow project role grants for groups

---

job-cleanup/cleanup.py
job-cleanup/kubernetes.py
monasca-transform/driver.py
monasca-transform/service_runner.py

Fix Python linter error - Part 3

---

kafka-init/create_topics.py
keystone-init/keystone_init.py

Fix Python linter error - Part 4

---

keystone/preload.py
monasca-agent-base/kubernetes_get_host.py
monasca-agent-base/template.py

Fix Python linter error - Part 5

---

webapp_demo/hello_django/hello_django/settings.py
webapp_demo/hello_django/hello_django/urls.py
webapp_demo/hello_django/hello_django/wsgi.py
webapp_demo/hello_django/manage.py
webapp_demo/hello_django/prometheus_app/admin.py
webapp_demo/hello_django/prometheus_app/apps.py
webapp_demo/hello_django/prometheus_app/models.py
webapp_demo/hello_django/prometheus_app/tests.py
webapp_demo/hello_django/prometheus_app/urls.py
webapp_demo/hello_django/prometheus_app/views.py

Fix Python linter error - Part 7

---

docker-compose.yml

Needed to listen on 0.0.0.0 not localhost. Use 18080 to lessen
chance of port collision

Make kafka-watcher work in docker-compose

---

job-cleanup/build.yml
job-cleanup/cleanup.py

Kubernetes 1.8.0 validates delete options more strictly, and we passed
a float instead of an int. Also removes propagationPolicy since it is
effectively a no-op.
Fixes monasca/monasca-helm#349

Fix job-cleanup for 1.8.0

---

monasca-agent-forwarder/start.sh

`set -x` was leaking several potentially secret  environment variable
values into log files.

Don't leak environment variables

---

monasca-thresh/Dockerfile
storm/build.yml
storm/templates/thresh-config.yml.j2

I have [proposed](https://review.openstack.org/541369) to remove MySQL Connector from monasca-thresh package and use Drizzle instead.
Please let me know if you see any issues with that.

Use Drizzle SQL connector in monasca-thresh

---

monasca-aggregator/Dockerfile
monasca-aggregator/build.yml

Building of confluent-kafka-go is currently broken on go v1.9.4 which
is currently shipping with alpine:edge [1]. This switches the image
build to alpine:3.7 which does now have this problem, however we may
run into issues upgrading to later versions if confluent-kafka-go
doesn't find a workaround for the underlying problem.
[1] https://github.com/confluentinc/confluent-kafka-go/issues/137

Fix monasca-aggregator build

---

monasca-aggregator/Dockerfile
monasca-aggregator/build.yml
monasca-aggregator/start.sh

Due to a recent Kubernetes CVE, subpath mounting (which allowed
single-file mounts to `/`) is broken. As the old aggregator image
expected to find its config files in `/`, it won't run in affected
versions.
This adds a workaround to `start.sh` so `config.yaml.j2` is copied
from `/config` and `aggregation-specifications.yaml` is copied from
in `/specs`. This allows ConfigMaps to be mounted to these individual
directories without any trouble.
As this is a breaking change to the aggregator image, this is a new
minor version release.

[aggregator] Move config files to subdirectories

---

ci.py

New versions of the Docker CLI warn about using `--password` and
require user confirmation, breaking CI. This switches to using
`--password-stdin`.

Use docker's `--password-stdin` in CI

---

.travis.yml

It looks like travis is experiencing issues with debian's shellcheck
package at the moment [1], so let's disable the shellcheck job for
now to unblock CI.
[1] https://github.com/travis-ci/travis-ci/issues/9484

Temporarily disable shellcheck to unblock CI

---

keystone-init/README.md
keystone-init/build.yml
keystone-init/keystone_init.py

This adds support for a new `domain_roles` attribute in group
definitions.

[keystone-init] add support for assigning domain-level roles to groups

---

grafana/Dockerfile
grafana/build.yml

This should publish `monasca/grafana:4.0.0-1.5.0` once merged.

Update grafana image to pull latest monasca app

---

logspout/Dockerfile
logspout/README.md
logspout/build.yml
logspout/modules.go

Added multiline-log feature
- From v3.2.5 logspout supports multiline-logs [1]
[1] https://github.com/gliderlabs/logspout/tree/v3.2.5#multiline-logging

Fix multiline logs

---

monasca-aggregator/build.yml
monasca-aggregator/config.yaml.j2

https://github.com/monasca/monasca-docker/issues/485
hello,aggregator can config log level in the config.yaml,but monasca-docker project lack of this property.this property should be available to users.

aggregator lack of loglevel property

---

monasca-api-python/Dockerfile
monasca-api-python/build.yml

Include missing dependencies. `pykafka` was removed from upper
constraints file.
Old code used for building monasca-api
https://review.openstack.org/#/c/417163 is not building anymore because
depended library included breaking changes.
Use newer version of monasca/python image.
Signed-off-by: Dobroslaw Zybort <dobroslaw.zybort@ts.fujitsu.com>

Update monasca-api to master and fix build

---

.travis.yml

Travis is showing:
This job ran using the default Python version, 
which will be updated to 3.6 on April 16th, 2019.
You can explicitly stay on the previous version
by specifying python: 2.7 in your .travis.yml.
Signed-off-by: Dobroslaw Zybort <dobroslaw.zybort@ts.fujitsu.com>

Force python 2.7 on Travis

---

monasca-thresh/build.yml

`master` tag will be overwritten by image coming from openstack repo.
Signed-off-by: Dobroslaw Zybort <dobroslaw.zybort@ts.fujitsu.com>

Remove master tag from monasca-thresh

---

.travis.yml

This is the output using the outdated URL:
```
$ wget "https://storage.googleapis.com/shellcheck/shellcheck-$SCVERSION.linux.x86_64.tar.xz"
--2020-06-03 06:43:52--  https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.204.128, 2607:f8b0:400c:c07::80
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.204.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 540 [application/x-xz]
Saving to: ‘shellcheck-stable.linux.x86_64.tar.xz’
0K                                                       100% 99.5M=0s
2020-06-03 06:43:52 (99.5 MB/s) - ‘shellcheck-stable.linux.x86_64.tar.xz’ saved [540/540]
before_install.2
0.01s$ tar --xz -xvf …
```

Update shellcheck URL
